services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopassword
    ports:
      - "5435:5432"
    expose:
      - "5432"    
    restart: unless-stopped